# Generated by Django 3.2.9 on 2022-04-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, choices=[('Los Angeles', 'Los Angeles'), ('Las Vegas', 'Las Vegas'), ('Miami', 'Miami')], max_length=128, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('basic_price', models.IntegerField(blank=True, null=True)),
                ('hotel_price', models.IntegerField(blank=True, null=True)),
                ('hotel_night_price', models.IntegerField(blank=True, null=True)),
                ('service_area_fee', models.IntegerField(blank=True, null=True)),
                ('night_price', models.IntegerField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices, zip codes',
            },
        ),
    ]
