# Generated by Django 3.2.9 on 2022-05-10 12:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_memberreferral'),
        ('users', '0003_twillionumber'),
        ('payment', '0002_payments_user'),
        ('subscriptions', '0002_initial'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('New', 'New'), ('Pending', 'Pending'), ('Upcoming', 'Upcoming'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=20, null=True)),
                ('micro_status', models.CharField(blank=True, choices=[('Valet on my way', 'Valet on my way'), ('Check In', 'Check In'), ('Working', 'Working'), ('No show', 'No show')], help_text='Notes about appointment`s process (such as "valet is on the way", etc)', max_length=100, null=True)),
                ('date', models.DateTimeField()),
                ('confirmed_by_client', models.BooleanField(default=False)),
                ('confirmed_by_valet', models.BooleanField(default=False)),
                ('refund', models.CharField(blank=True, choices=[('no', 'no'), ('full', 'full'), ('1/2', '1/2')], max_length=20, null=True)),
                ('notes', models.CharField(blank=True, max_length=1024, null=True)),
                ('number_of_people', models.IntegerField(default=1)),
                ('duration', models.DurationField(blank=True, default=datetime.timedelta(seconds=3600), null=True)),
                ('way_notification', models.BooleanField(default=False)),
                ('purchase_method', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_price', models.FloatField(default=0)),
                ('gift_card', models.CharField(blank=True, max_length=100, null=True)),
                ('initial_price', models.FloatField(default=0)),
                ('changed_valet', models.BooleanField(default=False)),
                ('changed_time', models.BooleanField(default=False)),
                ('changed_people', models.BooleanField(default=False)),
                ('people_added', models.BooleanField(default=False)),
                ('people_removed', models.BooleanField(default=False)),
                ('time_valet_set', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('noshow_timestamp', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Client', 'Client'), ('Valet', 'Valet')], max_length=31, null=True)),
                ('initial_confirm_by_valet', models.BooleanField(default=True)),
                ('additional_people', models.IntegerField(default=0)),
                ('time_valet_reminder', models.DateTimeField(auto_now_add=True)),
                ('has_feed', models.BooleanField(default=False)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True)),
                ('timezone', models.CharField(blank=True, choices=[('Los Angeles', 'Los Angeles'), ('Las Vegas', 'Las Vegas'), ('Miami', 'Miami')], max_length=32, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='users.address')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_appointments', to='users.client')),
                ('payments', models.ForeignKey(blank=True, help_text="User's payment credentials", null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.payments')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='users.twillionumber')),
                ('promocode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='membership.promocode')),
                ('subscription_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscription')),
                ('valet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valet_appointments', to='users.valet')),
            ],
        ),
    ]
