# Generated by Django 3.2.9 on 2022-06-20 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_payout_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoValetAppointments',
            fields=[
            ],
            options={
                'verbose_name': 'Appointment without valet',
                'verbose_name_plural': 'Appointment without valets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('appointments.appointment',),
        ),
    ]
