# Generated by Django 3.2.9 on 2022-05-16 07:51

from django.db import migrations, models
import django.db.models.deletion
import spray.users.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValetForSchedule',
            fields=[
            ],
            options={
                'verbose_name': 'Valet Schedule',
                'verbose_name_plural': 'Valets: Schedule',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.valet',),
            managers=[
                ('objects', spray.users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ValetScheduleOccupiedTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('valet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_offs', to='users.valet')),
            ],
            options={
                'verbose_name_plural': 'Valets: day offs / breaks',
            },
        ),
        migrations.CreateModel(
            name='ValetScheduleDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=32)),
                ('start_working_hours', models.TimeField(blank=True, null=True)),
                ('end_working_hours', models.TimeField(blank=True, null=True)),
                ('start_break_hours', models.TimeField(blank=True, null=True)),
                ('end_break_hours', models.TimeField(blank=True, null=True)),
                ('is_working', models.BooleanField(default=True)),
                ('is_required_to_work', models.BooleanField(default=False)),
                ('valet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_days', to='users.valet')),
            ],
            options={
                'verbose_name_plural': 'Valets: Working hours',
                'ordering': ('valet',),
            },
        ),
        migrations.CreateModel(
            name='ValetScheduleAdditionalTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('valet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_days', to='users.valet')),
            ],
            options={
                'verbose_name_plural': 'Valets: Additional working days',
            },
        ),
    ]
