# Generated by Django 3.2.9 on 2022-04-28 12:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_favoritevalets'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValetScheduleOccupiedTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('break_hours', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('valet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_offs', to='users.valet')),
            ],
            options={
                'verbose_name_plural': 'Valets: day offs / breaks',
            },
        ),
        migrations.CreateModel(
            name='ValetScheduleAdditionalTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('break_hours', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('valet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_days', to='users.valet')),
            ],
            options={
                'verbose_name_plural': 'Valets: Additional working days',
            },
        ),
    ]
