# Generated by Django 3.2.9 on 2022-06-06 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValetForSchedule',
        ),
    ]
