# Generated by Django 3.2.9 on 2022-05-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valetscheduleadditionaltime',
            old_name='break_hours',
            new_name='additional_hours',
        ),
    ]
