# Generated by Django 3.2.9 on 2022-05-11 07:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import spray.users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('schedule', '0003_alter_valetscheduleday_valet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValetForSchedule',
            fields=[
            ],
            options={
                'verbose_name': 'Valet Schedule',
                'verbose_name_plural': 'Valets: Schedule',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.valet',),
            managers=[
                ('objects', spray.users.managers.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='valetscheduleday',
            options={'ordering': ('valet',), 'verbose_name_plural': 'Valets: Working hours'},
        ),
        migrations.AlterField(
            model_name='valetscheduleday',
            name='break_hours',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valetscheduleday',
            name='working_hours',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
