# Generated by Django 3.2.9 on 2022-05-11 07:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import spray.utils.base_func


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20220511_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valetscheduleday',
            name='break_hours',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=spray.utils.base_func.default_break_hours),
        ),
        migrations.AlterField(
            model_name='valetscheduleday',
            name='working_hours',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=spray.utils.base_func.default_working_hours),
        ),
    ]
