# Generated by Django 3.2.9 on 2022-05-11 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20220511_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valetscheduleadditionaltime',
            name='additional_hours',
        ),
        migrations.RemoveField(
            model_name='valetscheduleday',
            name='break_hours',
        ),
        migrations.RemoveField(
            model_name='valetscheduleday',
            name='working_hours',
        ),
        migrations.RemoveField(
            model_name='valetscheduleoccupiedtime',
            name='break_hours',
        ),
    ]
