# Generated by Django 3.2.9 on 2022-04-19 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_merge_0005_address_0006_auto_20220412_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('Created', 'Created'), ('Deleted', 'Deleted')], max_length=32)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client')),
            ],
        ),
    ]
