# Generated by Django 3.2.9 on 2022-04-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220420_1442'),
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('value', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('code_type', models.CharField(choices=[('percent', 'percent'), ('discount', 'discount')], max_length=20)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('usage_counts', models.IntegerField(default=1)),
                ('is_agency', models.BooleanField(default=False, help_text="If selected, usage counts won't decrease")),
                ('agency_name', models.CharField(blank=True, help_text='Optional', max_length=100, null=True)),
                ('is_referral', models.BooleanField(default=False)),
                ('only_base_discount', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(to='users.Client')),
            ],
        ),
    ]
