# Generated by Django 3.2.9 on 2022-05-04 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='users',
            field=models.ManyToManyField(to='users.Client'),
        ),
        migrations.AddField(
            model_name='membershipevent',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client'),
        ),
    ]
