# Generated by Django 3.2.9 on 2022-04-28 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('membership', '0002_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipevent',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='users',
            field=models.ManyToManyField(to='client.Client'),
        ),
    ]
