# Generated by Django 3.2.9 on 2022-04-19 17:56

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='clientsubscription',
            managers=[
                ('create_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
