# Generated by Django 3.2.9 on 2022-04-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_clientsubscription_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='city',
            field=models.CharField(blank=True, choices=[('Los Angeles', 'Los Angeles'), ('Las Vegas', 'Las Vegas'), ('Miami', 'Miami')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('Stay Golden', 'Stay Golden'), ('Sunkissed', 'Sunkissed')], max_length=256, null=True),
        ),
    ]
