# Generated by Django 3.2.9 on 2022-04-28 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('subscriptions', '0004_alter_clientsubscription_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsubscription',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_subscriptions', to='client.client'),
        ),
    ]
