# Generated by Django 3.2.9 on 2022-04-28 09:26

from django.db import migrations, models
import django.db.models.deletion
import spray.users.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_auto_20220422_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('customer_status', models.CharField(blank=True, choices=[('New', 'New'), ('Returning', 'Returning'), ('Member', 'Member'), ('Subscriber', 'Subscriber')], max_length=100, null=True)),
                ('referal_code', models.CharField(blank=True, max_length=32, null=True)),
                ('notification_text_magic', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.user',),
            managers=[
                ('objects', spray.users.managers.UserManager()),
            ],
        ),
    ]
