# Generated by Django 3.2.9 on 2022-05-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwillioNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=31)),
            ],
        ),
    ]
