# Generated by Django 3.2.9 on 2022-04-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220330_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.RemoveField(
            model_name='client',
            name='test_client',
        ),
        migrations.RemoveField(
            model_name='valet',
            name='test_valet',
        ),
        migrations.AddField(
            model_name='client',
            name='customer_status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Returning', 'Returning'), ('Member', 'Member'), ('Subscriber', 'Subscriber')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='notification_text_magic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='referal_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='apple_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='docusign_envelope',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_sms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='valet',
            name='city',
            field=models.CharField(blank=True, choices=[('Los Angeles', 'Los Angeles'), ('Las Vegas', 'Las Vegas'), ('Miami', 'Miami')], help_text='valets field', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valet',
            name='emergency_name',
            field=models.CharField(blank=True, help_text='valets field', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='valet',
            name='feedback_popup_show_date',
            field=models.DateTimeField(blank=True, help_text='valets field', null=True),
        ),
        migrations.AddField(
            model_name='valet',
            name='license',
            field=models.CharField(blank=True, help_text='valets field', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='valet',
            name='notification_appointment',
            field=models.BooleanField(default=True, help_text='valets field'),
        ),
        migrations.AddField(
            model_name='valet',
            name='notification_only_working_hours',
            field=models.BooleanField(default=False, help_text='valets field'),
        ),
        migrations.AddField(
            model_name='valet',
            name='notification_shift',
            field=models.BooleanField(default=True, help_text='valets field'),
        ),
        migrations.AddField(
            model_name='valet',
            name='valet_available_not_on_call',
            field=models.BooleanField(default=False, help_text='valets field'),
        ),
        migrations.AddField(
            model_name='valet',
            name='valet_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='valet',
            name='valet_personal_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Personal phone'),
        ),
        migrations.AddField(
            model_name='valet',
            name='valet_reaction_time',
            field=models.IntegerField(default=0, help_text='valets field'),
        ),
    ]
