# Generated by Django 3.2.9 on 2022-04-08 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220330_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_string', models.CharField(max_length=128)),
                ('note_parking', models.CharField(blank=True, max_length=256, null=True)),
                ('selected_parking_option', models.CharField(blank=True, max_length=200, null=True)),
                ('is_hotel', models.BooleanField(default=False)),
                ('hotel_name', models.CharField(blank=True, max_length=200, null=True)),
                ('room_number', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('city', models.CharField(max_length=128)),
                ('zip_code', models.CharField(blank=True, max_length=128, null=True)),
                ('address_type', models.CharField(choices=[('Client', 'Client'), ('Valet', 'Valet')], default='Client', max_length=128)),
                ('state', models.CharField(blank=True, max_length=128, null=True)),
                ('country', models.CharField(default='USA', max_length=128)),
                ('apartment', models.CharField(blank=True, max_length=255, null=True)),
                ('gate_code', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='users.client')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
