# Generated by Django 3.2.9 on 2022-06-07 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_favoritevalets'),
        ('users', '0004_valetfeed_valetforschedule'),
    ]

    operations = [
    ]
