# Generated by Django 3.2.9 on 2022-06-08 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_valetfeed'),
        ('users', '0005_merge_20220607_1011'),
        ('users', '0005_merge_20220607_1027'),
    ]

    operations = [
    ]
