# Generated by Django 3.2.9 on 2022-04-12 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_address'),
        ('users', '0006_auto_20220412_1106'),
    ]

    operations = [
    ]
