# Generated by Django 3.2.9 on 2022-04-20 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_0005_address_0006_auto_20220412_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        # migrations.RemoveField(
        #     model_name='address',
        #     name='address',
        # ),
        # migrations.RemoveField(
        #     model_name='address',
        #     name='code',
        # ),
        # migrations.AddField(
        #     model_name='address',
        #     name='address_string',
        #     field=models.CharField(blank=True, max_length=128, null=True),
        # ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('Client', 'Client'), ('Valet', 'Valet')], default='Client', max_length=128),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='USA', max_length=128),
        ),
        migrations.AlterField(
            model_name='address',
            name='note_parking',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
