# Generated by Django 3.2.9 on 2022-04-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220420_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='test_client',
        ),
        migrations.RemoveField(
            model_name='valet',
            name='test_valet',
        ),
    ]
