# Generated by Django 3.2.9 on 2022-04-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('payment', '0003_alter_payments_user'),
        ('subscriptions', '0005_alter_clientsubscription_client'),
        ('blacklist', '0002_add_token_id'),
        ('authtoken', '0003_tokenproxy'),
        ('membership', '0003_auto_20220428_0926'),
        ('oauth2_provider', '0004_auto_20200902_2022'),
        ('account', '0002_email_max_length'),
        ('social_django', '0010_uid_db_index'),
        ('users', '0009_auto_20220422_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_string',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
