# Generated by Django 3.2.9 on 2022-05-04 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, choices=[('feedback', 'feedback'), ('inform', 'inform'), ('reschedule', 'reschedule'), ('appointment', 'appointment'), ('cc_expiring', 'cc_expiring'), ('new_message', 'new_message'), ('add_people', 'add_people'), ('pick_feed', 'pick_feed'), ('cancel_appointment', 'cancel_appointment'), ('reschedule_up', 'reschedule_up'), ('new_shift', 'new_shift'), ('close_feed', 'close_feed'), ('for_admin', 'for_admin')], max_length=30, null=True)),
                ('valet_id', models.IntegerField(blank=True, null=True)),
                ('appointment_id', models.IntegerField(blank=True, null=True)),
                ('chat_id', models.IntegerField(blank=True, null=True)),
                ('feed_id', models.IntegerField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('unread_messages', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
