# Generated by Django 3.2.9 on 2022-04-22 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='payments',
        #     name='user',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='users.client'),
        # ),
    ]
