# Generated by Django 3.2.9 on 2022-05-16 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_initial_price'),
        ('payment', '0002_payments_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled_by', models.CharField(choices=[('Admin', 'Admin'), ('Client', 'Client'), ('Valet', 'Valet')], max_length=31)),
                ('sum', models.IntegerField(default=0)),
                ('fee', models.FloatField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('refund_type', models.CharField(choices=[('Cancelled appointment', 'Cancelled appointment'), ('Custom/Partial', 'Custom/Partial')], default='Cancelled appointment', max_length=31)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='appointments.appointment')),
            ],
            options={
                'verbose_name_plural': 'Refunded orders',
            },
        ),
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(max_length=255)),
                ('is_additional', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='appointments.appointment')),
            ],
        ),
    ]
