# Generated by Django 3.2.9 on 2022-05-31 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_initial_price'),
        ('users', '0003_twillionumber'),
        ('payment', '0003_charges_refund'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Los Angeles', 'Los Angeles'), ('Las Vegas', 'Las Vegas'), ('Miami', 'Miami')], max_length=20)),
                ('locals', models.FloatField(default=0)),
                ('late_night', models.FloatField(default=0)),
                ('parking_fee', models.FloatField(default=0)),
                ('cancelled_fee', models.FloatField(default=0)),
                ('cancelled_no_show_fee', models.FloatField(default=0)),
                ('cancelled_no_show_fee_night', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Valets: Wages',
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('details', models.JSONField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=30, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='appointments.appointment')),
                ('valet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='users.valet')),
            ],
            options={
                'verbose_name_plural': 'Valets: Billing history',
            },
        ),
    ]
