# Generated by Django 3.2.9 on 2022-06-02 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_twillionumber'),
        ('payment', '0004_billingdetails_payout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_send', models.DateTimeField(blank=True, null=True)),
                ('valet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_details', to='users.valet')),
            ],
            options={
                'verbose_name_plural': 'Valets: Current earnings',
            },
        ),
    ]
